### ISSUE TITLE
Extract class constructor keywords args as compact json to reuse target class context

### ISSUE THREAD

**Issue by simontaurus** [OO-LD/awl-schema#2]
Calling a nested constructor of a dataclass 
```python
ClassA(a=1, b='b', c=ClassB(d=False))
```
results in a nested function call AST with keyword args:
```yaml
_type: Module
body:
  - _type: Expr
    value:
      - _type: Call
        args: []
        func:
          _type: Name
          id: ClassA
        keywords:
          - _type: keyword
            arg: a
            value:
              _type: Constant
              value: 1
          - _type: keyword
            arg: b
            value:
              _type: Constant
              value: b
          - _type: keyword
            arg: c
            value:
              _type: Call
              args: []
              func:
                _type: Name
                id: ClassB
              keywords:
                - _type: keyword
                  arg: d
                  value:
                    _type: Constant
                    value: false
type_ignores: []
```

(see also [playground](https://oo-ld.github.io/playground-awl/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAAlnhQqAD3EoA2qEryUIZVCgREKAPQOwYALTYAJgDoA5jCjKInhecA7mrkqqsg4KBoTWtvZOBmR0ENhUXtI%2BMWyaeGSIVPE2do7Obp6%2B%2FoHBoeGRamS5ILxQghDFlprtnQowHoSaAwp4YB6ChOYoABKFAApkUuJsAHKpXVojltMAakswZHgZCtqkBkZaBUUlieUpaRlZUjkgAL5vbOQvVFDIOxRsLNCgAVJY%2BX4KABuchEmxAw0GAKBc0Q%2B2wcNOOj0hg0IBhGK6CIJmI%2BbAAkkQ8YipoCUJSsedcWgQGMJrSgZSQVJSZ9wFIqNgbsj6UQAGJyG5fGhGEDTVEAYQQHn8cHgCiwaSWZCg0n%2BcrpqIASjAfNY5vAPEqtVIddIFJB9fLCgB5Tq23VSBQZIiy52IAAyVF9Fqt9Ag2s9CiIIngGGp2wNKMKYtjPDVCrk8jy2Iu1OuRISZWS%2BlS6Uy2Ra6wYHJQqbjsAQ0NhRP96N5bHBTsNhQAgi8RAxdAoANZUQQUaQef5bJFJ4GIADS48nUg8%2FZ8g6ow5zTMu%2BJbtdR7eKZLlLyPhWXkzeAF0vv4TpZewB1AMKXpEsCcbjiPmIZQwAoXgqCkKQ9UIGBdFAsh0ybL4oiJMYwD%2BKBbQgAAWBQyA4Mh9FQNC4TYMcqAgXgECoMAiF4EkaFQIhJSoPkOFodUWTaDoiQAWXGEQTjYNlJhMUAOL6SwAFF9AgL02FweBtzAVAAEY2FovFRKJTNsGzc8fH%2BYx72INN1M%2FQhq2KNhEwVAREEQXtvSghTlL5McJynfSRNMyxXNXQZOwvHYHPkyRlNUw92K8kAlSQcgdxAOSnJQFSD0JZzPk8zjCB8qdsIC1kgsS5K1IizLLGixBYpWeLHJCpKwtSywCDJDKxJAbK11ynxCHjWSasUuqUsxErWq0nSu1QAy2BjOMTNKkBzP6OdrMKRAACECtqpSXJXdyJpaol2r83TCCOhLNvqob9sIcrKo2%2FqivChihSYu9euC%2B6PkMs6PtekBP14U1JAFfTbw%2BIA%3D%3D))

The meaning of those keywords are usually defined within the dataclass. OO-LD specific, they are defined within the JSON-LD compatible context. In order to simply the handling of the actually passed data and direct application of the JSON-LD context it is helpful to represent the data directly as dict/JSON:

```yaml
a: 1
b: "b"
c:
  d: false
```

This would exactly match the dict serialization of the class and the dict used if you would write the argument as unpacked dict:
```py
ClassA(**{'a': 1, 'b': 'b', 'c': {'d': False}})
```

In order to persist the type information we can keep the class names as annotations / discriminators

```yaml
__class_name__: ClassA
a: 1
b: "b"
c:
  __class_name__: ClassB
  d: false
```

We can inject this compact notation back in the AST by replacing the original constructure call nodes recursively ascending

```yaml
_type: Module
body:
  - _type: Expr
    value:
      - __class_name__: ClassA
        a: 1
        b: "b"
        c:
          __class_name__: ClassB
          d: false
type_ignores: []
```

This would work in any constellation, especially if the constructor is argument of a regular function call

```python
my_func(ClassA(a=1, b='b', c=ClassB(d=False)))
```

```yaml
_type: Module
body:
  - _type: Expr
    value:
      _type: Call
      func:
        _type: Name
        id: my_func
      keywords: []
      args:
        - __class_name__: ClassA
          a: 1
          b: "b"
          c:
            __class_name__: ClassB
            d: false

type_ignores: []
```

Finally we can apply the class context as type scoped context
```yaml
'@context':
  - awl: https://oo-ld.github.io/awl-schema/
    ex: https://example.org/
    '@base': https://oo-ld.github.io/awl-schema/
    _type: '@type'
    id: '@id'
    body: awl:HasPart
    Name:
      '@id': awl:Variable
      '@context':
        '@base': https://example.org/
    targets: awl:HasTarget
    value:
      '@id': awl:HasValue
      '@context':
        value: '@value'
    If:
      '@id': awl:If
      '@context':
        body: awl:IfTrue
    orelse: awl:IfFalse
    test: awl:HasCondition
    comparators: awl:HasRightHandComparator
    ops: awl:HasOperator
    left: awl:HasLeftHandComparator
    func:
      '@id': awl:HasFunctionCall
      '@context':
        '@base': https://example.org/
        Name: awl:Function
        value: awl:HasValue
    args: awl:HasArgument
    keywords:
      '@id': awl:HasKeywordArgument
      '@context':
        value: awl:HasValue
    arg: awl:HasKey
    __class_name__: '@type' # new content below
    ClassA:
      '@id': ex:ClassA
      '@context':
        a: ex:a
        b: ex:b
        c:
          '@id': ex:c
          '@type': '@id'
    ClassB:
      '@id': ex:ClassB
      '@context':
        d: ex:d
title: AWL
type: object
```

resulting in

```turtle
@prefix ns0: <https://oo-ld.github.io/awl-schema/> .
@prefix ns1: <https://example.org/> .

<https://example.org/my_func> a <https://oo-ld.github.io/awl-schema/Function> .
[]
  a <https://oo-ld.github.io/awl-schema/Module> ;
  ns0:HasPart [
    a ns0:Expr ;
    ns0:HasValue [
      a ns0:Call ;
      ns0:HasArgument [
        a ns1:ClassA ;
        ns1:a 1 ;
        ns1:b "b" ;
        ns1:c [
          a ns1:ClassB ;
          ns1:d false
        ]
      ] ;
      ns0:HasFunctionCall ns1:my_func
    ]
  ] .
```
(see [playground](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%7B%22awl%22%3A%22https%3A%2F%2Foo-ld.github.io%2Fawl-schema%2F%22%2C%22ex%22%3A%22https%3A%2F%2Fexample.org%2F%22%2C%22%40base%22%3A%22https%3A%2F%2Foo-ld.github.io%2Fawl-schema%2F%22%2C%22_type%22%3A%22%40type%22%2C%22id%22%3A%22%40id%22%2C%22body%22%3A%22awl%3AHasPart%22%2C%22Name%22%3A%7B%22%40id%22%3A%22awl%3AVariable%22%2C%22%40context%22%3A%7B%22%40base%22%3A%22https%3A%2F%2Fexample.org%2F%22%7D%7D%2C%22targets%22%3A%22awl%3AHasTarget%22%2C%22value%22%3A%7B%22%40id%22%3A%22awl%3AHasValue%22%2C%22%40context%22%3A%7B%22value%22%3A%22%40value%22%7D%7D%2C%22If%22%3A%7B%22%40id%22%3A%22awl%3AIf%22%2C%22%40context%22%3A%7B%22body%22%3A%22awl%3AIfTrue%22%7D%7D%2C%22orelse%22%3A%22awl%3AIfFalse%22%2C%22test%22%3A%22awl%3AHasCondition%22%2C%22comparators%22%3A%22awl%3AHasRightHandComparator%22%2C%22ops%22%3A%22awl%3AHasOperator%22%2C%22left%22%3A%22awl%3AHasLeftHandComparator%22%2C%22func%22%3A%7B%22%40id%22%3A%22awl%3AHasFunctionCall%22%2C%22%40context%22%3A%7B%22%40base%22%3A%22https%3A%2F%2Fexample.org%2F%22%2C%22Name%22%3A%22awl%3AFunction%22%2C%22value%22%3A%22awl%3AHasValue%22%7D%7D%2C%22args%22%3A%22awl%3AHasArgument%22%2C%22keywords%22%3A%7B%22%40id%22%3A%22awl%3AHasKeywordArgument%22%2C%22%40context%22%3A%7B%22value%22%3A%22awl%3AHasValue%22%7D%7D%2C%22arg%22%3A%22awl%3AHasKey%22%2C%22__class_name__%22%3A%22%40type%22%2C%22ClassA%22%3A%7B%22%40id%22%3A%22ex%3AClassA%22%2C%22%40context%22%3A%7B%22a%22%3A%22ex%3Aa%22%2C%22b%22%3A%22ex%3Ab%22%2C%22c%22%3A%7B%22%40id%22%3A%22ex%3Ac%22%2C%22%40type%22%3A%22%40id%22%7D%7D%7D%2C%22ClassB%22%3A%7B%22%40id%22%3A%22ex%3AClassA%22%2C%22%40context%22%3A%7B%22d%22%3A%22ex%3Ad%22%7D%7D%7D%5D%2C%22_type%22%3A%22Module%22%2C%22body%22%3A%5B%7B%22_type%22%3A%22Expr%22%2C%22value%22%3A%7B%22_type%22%3A%22Call%22%2C%22func%22%3A%7B%22_type%22%3A%22Name%22%2C%22id%22%3A%22my_func%22%7D%2C%22keywords%22%3A%5B%5D%2C%22args%22%3A%5B%7B%22__class_name__%22%3A%22ClassA%22%2C%22a%22%3A1%2C%22b%22%3A%22b%22%2C%22c%22%3A%7B%22__class_name__%22%3A%22ClassB%22%2C%22d%22%3Afalse%7D%7D%5D%7D%7D%5D%2C%22type_ignores%22%3A%5B%5D%7D))

<details>
<summary>Drafts to keep dict representation side-by-side with the original AST</summary>

```yaml
_type: Module
body:
  - _type: Expr
    __value_dict__: # parent annotation
        __class_name__: ClassA
        a: 1
        b: "b"
        c:
          __class_name__: ClassB
          d: false
    value:
      - _type: Call
        args: []
        func:
          _type: Name
          id: ClassA
        __keywords_dict__: # self annotation
            __class_name__: ClassA
            a: 1
            b: "b"
            c:
              __class_name__: ClassB
              d: false
        keywords:
          - _type: keyword
            arg: a
            value:
              _type: Constant
              value: 1
          - _type: keyword
            arg: b
            value:
              _type: Constant
              value: b
          - _type: keyword
            arg: c
            value:
              _type: Call
              args: []
              func:
                _type: Name
                id: ClassB
              keywords:
                - _type: keyword
                  arg: d
                  value:
                    _type: Constant
                    value: false
type_ignores: []
```

```python
my_func(ClassA(a=1, b='b', c=ClassB(d=False)))
```

```yaml
_type: Module
body:
  - _type: Expr
    value:
      _type: Call
      func:
        _type: Name
        id: my_func
      keywords: []
      __value_dict__: # parent annotation
          __class_name__: ClassA
          a: 1
          b: "b"
          c:
            __class_name__: ClassB
            d: false
      args:
        - _type: Call
          args: []
          func:
            _type: Name
            id: ClassA
          __keywords_dict__: # self annotation
              __class_name__: ClassA
              a: 1
              b: "b"
              c:
                __class_name__: ClassB
                d: false
          keywords:
            - _type: keyword
              arg: a
              value:
                _type: Constant
                value: 1
            - _type: keyword
              arg: b
              value:
                _type: Constant
                value: b
            - _type: keyword
              arg: c
              value:
                _type: Call
                args: []
                func:
                  _type: Name
                  id: ClassB
                keywords:
                  - _type: keyword
                    arg: d
                    value:
                      _type: Constant
                      value: false
type_ignores: []
```

</details
